name = "codelab"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_URL = "https://codelab.lucasangelo.dev"
PIN_LENGTH = "6"
RESEND_FROM_EMAIL = "CodeLab <noreply@codelab.lucasangelo.dev>"

[[d1_databases]]
binding = "DB"
database_name = "codelab-db"
database_id = "f4496e17-db09-44e8-be10-dfe533ebbdba"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "codelab-storage"
